### ISSUE TITLE
[Anon] Bug report: Dwarfs.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kings-of-war-vanguard#10]
**File:** Dwarfs.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Dwarf Mastiff Packmaster mastiff packmaster is a warrior, not support ( v.1.1 )

**Comment by BitPsycho** [comment]
Fixed with upcoming 1.10 release - thanks for reporting.
