### ISSUE TITLE
[Anon] Bug report: The_Herd.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kings-of-war-vanguard#3]
**File:** The_Herd.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Lycan
Sp 4 should be Sp 7

Adding more words because the bug report form requires 50+ characters.

**Comment by BitPsycho** [comment]
Fixed. 

Thanks for reporting :-)
