### ISSUE TITLE
[Anon] Bug report: Kingdoms_of_men.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kings-of-war-vanguard#6]
**File:** Kingdoms_of_men.catz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** The point cost for grunts is wrong.  It should be 7 and instead it is 11.

**Comment by BitPsycho** [comment]
Fixed. Will be added in next coming release.
