### ISSUE TITLE
[Anon] Bug report: Ogres.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kings-of-war-vanguard#7]
**File:** Ogres.catz

**BattleScribe version:** 2.01.22

**Platform:** Android

**Dropbox:** Yes

**Description:** The ogres warband seems to be for larger games buggy giving errors saying I can't have any troops when input them but if I don't input troops it's complains saying I need them I hope this helps

**Comment by BitPsycho** [comment]
Not sure what is meant with 'larger games' but tried createing a war band of 500 points and did not have any issue at all ... everything works as intented, following the rules as stipulated by the Vanguard rulebook.

The number of allowed troops ( assuming grunts / warriors is meant here ) is minimum 5 and furthermore drives the number of other units one can take.  For every 3 normal troops 1 command / spellcaster / support can be taken.  Adding too many of the latter will give errors if not enough troops are available.  Maybe that's what happened here.

**Comment by BitPsycho** [comment]
Issues were caused as no max points were entered when creating a normal war band ... as the force points are 0 most rules will invalidate.  This issue does not occur when people create a zero points cap small war band as the number of validation rules are very limited and don't rely on the total force points.  Hence the confusion.
