### ISSUE TITLE
[Anon] Bug report: Varangur.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/kings-of-war-vanguard#9]
**File:** Varangur.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** Hello :)
There is a mistake within the 'Night Raider' unit entry in the Varangur Warband list. The 'Night Raider' has the wrong amount of D8's for Ranged and Melee, it has to be 2D8 for both :).
Keep up the amazing work and thanks for fixing in advance!
Best regards,
Martin

**Comment by BitPsycho** [comment]
Fixed. Will be available in next release.
